markdown: rdiscount
permalink: /:title/
url: http://anaer.github.io
name: anaer
author: anaer
qq:
email:
duoshuo:
uyan: 1958077
beian:
cnzz:
weibo:
github: anaer
pygments: true
safe: true
paginate: 20
about: ""
